### ISSUE TITLE
Plonk-Prototype Tracking Issue

### ISSUE THREAD

**Issue by tsunrise** [Manta-Network/Plonk-Prototype#1]
We can use this thread to discuss the TODO lists for this repo. Feel free to add more. 

## Basic Gadgets
- [x] CRH / Hash Function
- [ ] Merkle Tree path verification (Will use CRH / Hash function)
~~Incremental Merkle Tree (?)~~ (removed, as not needed for this project)
- [ ] Commitment Schemes (need a scheme for each of the following constraints)
    - [ ] `Output: Scalar`
    - [ ] `Randomness: Scalar`

~~PRFs~~ (removed, as not needed for new spec)

## Some higher level gadgets
- [ ] Probably all circuits [here](https://github.com/Manta-Network/manta-api/blob/97d5e5fcaa52ccc1018e271a61e27282a9f48f80/src/zkp/circuit.rs)?

**Comment by tsunrise** [comment]
All works have been moved to [manta-rs](https://github.com/Manta-Network/manta-rs)
